# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 02:46
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='SouthTexasCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=32140)),
            ],
        ),
    ]
